In [1]:
import pandas as pd
#df = pd.read_csv("amazon_cells_labelled.tsv",sep='\t')
with open("amazon_cells_labelled.tsv", "r") as file:
    data = file.read()

print(type(data))



<class 'str'>


In [2]:
    df = pd.read_csv(
        "amazon_cells_labelled.tsv",
        sep='\t',
        encoding = 'utf-8',
        header=None,
        names=['msg','lbl'], 
    )


In [3]:
df.groupby("lbl", dropna=False).count()

msg
lbl       
0.0    500
1.0    500
NaN  13609

In [6]:
display (
df[df['lbl'].isnull()],
df[df['lbl'] == 1].head(5),
df[(df['lbl'] == 1) | (df['lbl'] == 0)]
)

msg  lbl
0      I try not to adjust the volume setting to avoi...  NaN
3            I thought Motorola made reliable products!.  NaN
4                             Battery for Motorola Razr.  NaN
6      When I got this item it was larger than I thou...  NaN
7      (I looked for one that specifically said DCU-6...  NaN
...                                                  ...  ...
14604        The screen on my phone said "Not Charging".  NaN
14605   This is my 4th Samsung cell phone with T-Mobile.  NaN
14606                                     great company.  NaN
14607  The "call" and "hang-up" keys are now properly...  NaN
14608              Hopefully the Kyocera will be better!  NaN

[13609 rows x 2 columns]

msg  lbl
2                   Good case, Excellent value.  1.0
5                        Great for the jawbone.  1.0
11                            The mic is great.  1.0
17  If you are Razr owner...you must have this!  1.0
24              And the sound quality is great.  1.0

msg  lbl
1     So there is no way for me to plug it in here i...  0.0
2                           Good case, Excellent value.  1.0
5                                Great for the jawbone.  1.0
10    Tied to charger for conversations lasting more...  0.0
11                                    The mic is great.  1.0
...                                                 ...  ...
2901  The screen does get smudged easily because it ...  0.0
2906  What a piece of junk.. I lose more calls on th...  0.0
2910                       Item Does Not Match Picture.  0.0
2911  The only thing that disappoint me is the infra...  0.0
2913  You can not answer calls with the unit, never ...  0.0

[1000 rows x 2 columns]

In [6]:
df

msg  lbl
0      I try not to adjust the volume setting to avoi...  NaN
1      So there is no way for me to plug it in here i...  0.0
2                            Good case, Excellent value.  1.0
3            I thought Motorola made reliable products!.  NaN
4                             Battery for Motorola Razr.  NaN
...                                                  ...  ...
14604        The screen on my phone said "Not Charging".  NaN
14605   This is my 4th Samsung cell phone with T-Mobile.  NaN
14606                                     great company.  NaN
14607  The "call" and "hang-up" keys are now properly...  NaN
14608              Hopefully the Kyocera will be better!  NaN

[14609 rows x 2 columns]

# pregunta1

In [6]:

df_tagged = df[(df['lbl'] == 1) | (df['lbl'] == 0)]
df_untagged =df[df['lbl'].isnull()]
x_tagged = df_tagged["msg"]
y_tagged = df_tagged["lbl"]
x_untagged = df_untagged["msg"]
y_untagged = df_untagged["lbl"]


In [130]:
y_untagged 

0       NaN
3       NaN
4       NaN
6       NaN
7       NaN
         ..
14604   NaN
14605   NaN
14606   NaN
14607   NaN
14608   NaN
Name: lbl, Length: 13609, dtype: float64

# pregunta2

In [7]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(
        x_tagged,
        y_tagged,
        test_size=0.1,
        random_state=12345,
    )

In [24]:
type(x_train)

pandas.core.series.Series

* ojo esto es explicacion de train_test_split

In [10]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()

X = digits.data
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.5,
    shuffle=False,
)


In [22]:
y.shape

(1797,)

# pregunta3

In [93]:
def pregunta_03():
    """
    Construcción de un analizador de palabras
    -------------------------------------------------------------------------------------
    """
    # Importe el stemmer de Porter
    # Importe CountVectorizer
    from nltk.stem.porter import PorterStemmer
    from sklearn.feature_extraction.text import CountVectorizer

    # Cree un stemeer que use el algoritmo de Porter.
    stemmer = PorterStemmer()
    #dfsteam = x_train.apply(lambda x: " ".join([stemmer.stem(w) for w in x.split()]))

    # Cree una instancia del analizador de palabras (build_analyzer)
    vectorizer3 = CountVectorizer(analyzer="word",token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]+\b", lowercase=True)
    analyzer = vectorizer3.build_analyzer()
    
    # Retorne el analizador de palabras
    return lambda x: (stemmer.stem(w) for w in analyzer(x))

In [94]:
analyzer = pregunta_03()
result = list(
        analyzer("Buyer Beware, you could flush money right down the toilet.")
    )
result

['buyer',
 'bewar',
 'you',
 'could',
 'flush',
 'money',
 'right',
 'down',
 'the',
 'toilet']

## Analisis

In [14]:
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
stemmer = PorterStemmer()
dfsteam = x_train.apply(lambda x: " ".join([stemmer.stem(w) for w in x.split()]))
display(
    dfsteam.iloc[0],
    x_train,
    dfsteam
)


'buyer beware, you could flush money right down the toilet.'

256     Buyer Beware, you could flush money right down...
2720    I was very impressed with the price of the cases.
1856              I am more than happy with this product.
731     I was very excited to get this headset because...
2713                               Buttons are too small.
                              ...                        
1308                                   Price is good too.
339               The BT headset was such a disapoinment.
900                                         Great phone!.
1474                                    A Disappointment.
1468    After charging overnight, these batteries work...
Name: msg, Length: 900, dtype: object

256     buyer beware, you could flush money right down...
2720       i wa veri impress with the price of the cases.
1856               i am more than happi with thi product.
731     i wa veri excit to get thi headset becaus i th...
2713                                button are too small.
                              ...                        
1308                                   price is good too.
339                the bt headset wa such a disapoinment.
900                                         great phone!.
1474                                    a disappointment.
1468     after charg overnight, these batteri work great.
Name: msg, Length: 900, dtype: object

In [86]:
Analizer = CountVectorizer(
    #analyzer="word",
    lowercase=True,
    preprocessor=None,
    tokenizer=None,
    #stop_words="english",
    token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]+\b",
    #token_pattern="(?u)\b\w\w+\b",
    #binary=True,
    binary=False,
    max_df=1.0,
    min_df=1,
    #max_features=None,
    
)
analyze = Analizer.build_analyzer()
analyze(dfsteam.iloc[0])

['buyer',
 'beware',
 'you',
 'could',
 'flush',
 'money',
 'right',
 'down',
 'the',
 'toilet']

In [22]:
vocabulary = Analizer.get_feature_names()


NotFittedError: Vocabulary not fitted or provided

"OJO - jememplo"

In [90]:
vectorizer = CountVectorizer(
        # -------------------------------------------------------------
        # Convert all characters to lowercase before tokenizing.
        lowercase=True,
        # -------------------------------------------------------------
        # Override the preprocessing (strip_accents and lowercase)
        # stage
        preprocessor=None,
        # -------------------------------------------------------------
        # Override the string tokenization step while preserving the
        # preprocessing and n-grams generation steps. Only applies if
        # analyzer == 'word'.
        tokenizer=None,
        # -------------------------------------------------------------
        # If ‘english’, a built-in stop word list for English is used.
        #stop_words="english",
        # -------------------------------------------------------------
        # Regular expression denoting what constitutes a “token”, only
        # used if analyzer == 'word'. The default regexp select tokens
        # of 2 or more alphanumeric characters (punctuation is
        # completely ignored and always treated as a token separator).
        token_pattern=r"(?u)\b\w\w+\b",
        # -------------------------------------------------------------
        # When building the vocabulary ignore terms that have a
        # document frequency strictly higher than the given threshold
        # (corpus-specific stop words). If float, the parameter
        # represents a proportion of documents, integer absolute counts.
        # This parameter is ignored if vocabulary is not None.
        max_df=1.0,
        # -------------------------------------------------------------
        # When building the vocabulary ignore terms that have a
        # document frequency strictly lower than the given threshold.
        # This value is also called cut-off in the literature. If float,
        # the parameter represents a proportion of documents, integer
        # absolute counts.
        min_df=1,
        # -------------------------------------------------------------
        # If not None, build a vocabulary that only consider the top
        # max_features ordered by term frequency across the corpus.
        max_features=None,
        # -------------------------------------------------------------
        # If True, all non zero counts are set to 1. This is useful for
        # discrete probabilistic models that model binary events rather
        # than integer counts.
        binary=False,
    )
analyze1 = vectorizer.build_analyzer()
analyze1("Buyer Beware, you could flush money right down the toilet. ")

['buyer',
 'beware',
 'you',
 'could',
 'flush',
 'money',
 'right',
 'down',
 'the',
 'toilet']

In [78]:
vectorizer3 = CountVectorizer(analyzer="word",token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]+\b")
analyze2 = vectorizer3.build_analyzer()
analyze2("Buyer Beware, you could flush money right down the toilet. ")

['buyer',
 'beware',
 'you',
 'could',
 'flush',
 'money',
 'right',
 'down',
 'the',
 'toilet']

# pregunta4

In [112]:
def pregunta_04():
    """
    Especificación del pipeline y entrenamiento
    -------------------------------------------------------------------------------------
    """

    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.model_selection import GridSearchCV
    from sklearn.pipeline import Pipeline
    from sklearn.naive_bayes import BernoulliNB
   
    # Cargue las variables.
    #x_train, x_test, y_train, y_test = pregunta_02()

    # Obtenga el analizador de la pregunta 3.
    analyzer = pregunta_03()

    # Cree una instancia de CountVectorizer que use el analizador de palabras
    # de la pregunta 3. Esta instancia debe retornar una matriz binaria. El
    # límite superior para la frecuencia de palabras es del 100% y un límite
    # inferior de 5 palabras. Solo deben analizarse palabras conformadas por
    # letras.

    countVectorizer = CountVectorizer(
            analyzer=analyzer,
            lowercase=True,
            stop_words="english",
            token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]+\b",
            binary=True,
            max_df=1.0,
            min_df=5,
    )

    #dtm = countVec.fit_transform(df.stemmed)

    # Cree un pipeline que contenga el CountVectorizer y el modelo de BernoulliNB.
    bnb = BernoulliNB()
    pipeline = Pipeline(
            steps=[
                ("countVectorizer", countVectorizer),
                ("bernoulli", bnb),
            ],
    )

    # Defina un diccionario de parámetros para el GridSearchCV. Se deben
    # considerar 10 valores entre 0.1 y 1.0 para el parámetro alpha de
    # BernoulliNB.
    dicparam = {
            "bernoulli__alpha": np.arange(0.1, 1.01, 0.1),
        }

    # Defina una instancia de GridSearchCV con el pipeline y el diccionario de
    # parámetros. Use cv = 5, y "accuracy" como métrica de evaluación
    gridSearchCV = GridSearchCV(
            estimator=pipeline,
            param_grid=dicparam,
            cv=5,
            scoring="accuracy",
            refit=True,
            return_train_score=True,
        )

    # Búsque la mejor combinación de regresores
    gridSearchCV.fit(x_train, y_train)

    # Retorne el mejor modelo
    return gridSearchCV


In [95]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import BernoulliNB
   
#x_train, x_test, y_train, y_test = pregunta_02()

analyzer = pregunta_03()

countVectorizer = CountVectorizer(
        analyzer=analyzer,
        lowercase=True,
        stop_words="english",
        token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]+\b",
        binary=True,
        max_df=1.0,
        min_df=5,
)


In [96]:
bernoulliBN = BernoulliNB()
pipeline = Pipeline(
        steps=[
            ("countVectorizer", countVectorizer),
            ("bernoulli", bernoulliBN),
        ],
)

In [97]:
import numpy as np
dicparam = {
        "bernoulli__alpha": np.arange(0.1, 1.01, 0.1),
    }

In [98]:
dicparam

{'bernoulli__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])}

In [99]:
 gridSearchCV = GridSearchCV(
        estimator=pipeline,
        param_grid=dicparam,
        cv=5,
        scoring="accuracy",
        refit=True,
        return_train_score=True,
    )


In [100]:
gridSearchCV.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('countVectorizer',
                                        CountVectorizer(analyzer=<function pregunta_03.<locals>.<lambda> at 0x7fc7a24e60d0>,
                                                        binary=True, min_df=5,
                                                        stop_words='english',
                                                        token_pattern='(?u)\\b[a-zA-Z][a-zA-Z]+\\b')),
                                       ('bernoulli', BernoulliNB())]),
             param_grid={'bernoulli__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])},
             return_train_score=True, scoring='accuracy')

In [87]:
gridSearchCV.estimator.get_params().keys()

dict_keys(['memory', 'steps', 'verbose', 'countVectorizer', 'Bernoulli', 'countVectorizer__analyzer', 'countVectorizer__binary', 'countVectorizer__decode_error', 'countVectorizer__dtype', 'countVectorizer__encoding', 'countVectorizer__input', 'countVectorizer__lowercase', 'countVectorizer__max_df', 'countVectorizer__max_features', 'countVectorizer__min_df', 'countVectorizer__ngram_range', 'countVectorizer__preprocessor', 'countVectorizer__stop_words', 'countVectorizer__strip_accents', 'countVectorizer__token_pattern', 'countVectorizer__tokenizer', 'countVectorizer__vocabulary', 'Bernoulli__alpha', 'Bernoulli__binarize', 'Bernoulli__class_prior', 'Bernoulli__fit_prior'])

In [102]:
gridSearchCV.best_score_

0.7822222222222223

In [104]:
best_parameters = gridSearchCV.best_estimator_.get_params()
for param_name in sorted(dicparam):
    print("{:>30s}: {:s}".format(param_name, repr(best_parameters[param_name])))


              bernoulli__alpha: 0.1


In [108]:
gridSearchCV.score(x_train, y_train)

0.8766666666666667

In [107]:
gridSearchCV.score(x_test, y_test).round(4)

0.77

# Pregunta 5

In [109]:
def pregunta_05():
    """
    Evaluación del modelo
    -------------------------------------------------------------------------------------
    """

    # Importe confusion_matrix
    from sklearn.metrics import confusion_matrix

    # Obtenga el pipeline de la pregunta 3.
    gridSearchCV = pregunta_04()

    # Cargue las variables.
    x_train, x_test, y_train, y_test = pregunta_02()

    # Evalúe el pipeline con los datos de entrenamiento usando la matriz de confusion.
    cfm_train = confusion_matrix(
        y_true=y_train,
        y_pred=gridSearchCV.predict(x_train),
    )

    cfm_test = confusion_matrix(
        y_true=y_test,
        y_pred=gridSearchCV.predict(x_test),
    )

    # Retorne la matriz de confusion de entrenamiento y prueba
    return cfm_train, cfm_test


In [113]:
from sklearn.metrics import confusion_matrix
gridSearchCV = pregunta_04()


In [120]:
display(
    y_train,
    gridSearchCV.predict(x_train),
)

256     0.0
2720    1.0
1856    1.0
731     1.0
2713    0.0
       ... 
1308    1.0
339     0.0
900     1.0
1474    0.0
1468    1.0
Name: lbl, Length: 900, dtype: float64

array([0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0.

# Pregunta 6

In [121]:
cfm_train = confusion_matrix(
    y_true=y_train,
    y_pred=gridSearchCV.predict(x_train),
    )
cfm_train

array([[394,  60],
       [ 51, 395]])

In [122]:
cfm_test = confusion_matrix(
        y_true=y_test,
        y_pred=gridSearchCV.predict(x_test),
    )
display(
    y_test,
    gridSearchCV.predict(x_test),
    cfm_test
)

402     0.0
2386    0.0
835     0.0
1424    0.0
2722    1.0
       ... 
2080    1.0
2269    1.0
1790    1.0
270     0.0
2222    1.0
Name: lbl, Length: 100, dtype: float64

array([0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.])

array([[32, 14],
       [ 9, 45]])

In [123]:
gridSearchCV = pregunta_04()


In [124]:
y_untagged_pred = gridSearchCV.predict(x_untagged)

In [126]:
y_untagged_pred.shape

(13609,)

In [136]:
y_untagged_pred

array([0., 1., 1., ..., 1., 0., 0.])

In [139]:
type(x_untagged)

pandas.core.series.Series

In [133]:
df_untagged['y_untagged_pred']=y_untagged_pred[0]

/tmp/ipykernel_59344/3609501534.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_untagged['y_untagged_pred']=y_untagged_pred


In [137]:
df_untagged

msg  lbl  y_untagged_pred
0      I try not to adjust the volume setting to avoi...  NaN              0.0
3            I thought Motorola made reliable products!.  NaN              1.0
4                             Battery for Motorola Razr.  NaN              1.0
6      When I got this item it was larger than I thou...  NaN              1.0
7      (I looked for one that specifically said DCU-6...  NaN              1.0
...                                                  ...  ...              ...
14604        The screen on my phone said "Not Charging".  NaN              0.0
14605   This is my 4th Samsung cell phone with T-Mobile.  NaN              1.0
14606                                     great company.  NaN              1.0
14607  The "call" and "hang-up" keys are now properly...  NaN              0.0
14608              Hopefully the Kyocera will be better!  NaN              0.0

[13609 rows x 3 columns]

In [145]:
data = np.array(['the worst item i ever bought', 'i love it','think twice before buy it','great product'])
  
ser = pd.Series(data)
pred = gridSearchCV.predict(ser)
pred

array([0., 1., 0., 1.])

In [ ]:
data = np.array(['g', 'e', 'e', 'k', 's'])
  
ser = pd.Series(data)